### ISSUE TITLE
use in js file for website?

### ISSUE THREAD

**Issue by v3nt** [DamonOehlman/detect-browser#63]
How can i run this in a js file for website? 

`scripts.js:10851 Uncaught ReferenceError: require is not defined`

Adding detect-browser/index.js to my main scripts file via grunt.

Any pointers/quick fixes welcome!

**Comment by DamonOehlman** [comment]
Hey @v3nt - apologies for the delay in getting back to you.  The package is definitely very [`browserify`](https://github.com/browserify/browserify) focused at the present.

I do agree though it's probably something that would be useful as a standalone script.  Rather than include something in this repository I think it's probably better if we look at a way to publish the script to [cdnjs](https://cdnjs.com/) or similar.  I'll try to look into that over this coming weekend.

**Comment by v3nt** [comment]
@DamonOehlman thanks - yes seems like it would be fairly possible. I'm not really sure what 'browserify' is tbh...

**Comment by 5punk** [comment]
Closing as inactive.

Creating separate issue for tracking progress on new architecture.
