### ISSUE TITLE
I want to distinguish iPad from iOS

### ISSUE THREAD

**Issue by euxn23** [DamonOehlman/detect-browser#69]
Now using `browser.os` returns `'iOS'` if browser is both iPad and iPhone.
I want extra function `browser.isMobile()` or parameter `browser.devise`.
How do you think? @DamonOehlman 
(And if you say yes, I'd like to help develop it.)

**Comment by DamonOehlman** [comment]
@euxn23 I think we'd need to put a bit of thought into it.  I have a `3.0` release planned (see #65) and this would be the perfect opportunity to add some functionality like this.

Did you have any parameters that you thought would mean that device A was considered mobile while device B was not?  The comparison between iPad and iPhone is a good one.  I probably would have considered both mobile, but if you can talk through your specific use case perhaps we can work something out.

**Comment by vstets** [comment]
@DamonOehlman When are you going to release 3.0 version? Pull request #65 was created May 5, 2018, one month ago.

**Comment by DamonOehlman** [comment]
@vstets Yep, was looking to get some feedback from the other contributors on this package.  I'll ping in that PR now.

**Comment by euxn23** [comment]
In my usecase, rewrite viewport if iPad.
Using codes is as below.

```
export default function isMobile(): boolean {
  const ua = navigator.useragent
  if (ua.indexOf('iPad') > 0) return false
  return (
    ua.indexOf('iPhone') > 0 ||
    ua.indexOf('iPod') > 0 ||
    ua.indexOf('Android') > 0 ||
    ua.indexOf('Mobile') > 0
  )
}
```

If this doesn't have any problem, I'll make a pull-request.

**Comment by DamonOehlman** [comment]
@vstets @euxn23 So PR #65 will be merged shortly, however, I won't do the `3.x` release until we have decided exactly how we want to tackle this.  I personally feel like we might be overstepping what `detect-browser` was originally intended for, but can understand why you want this functionality.

So going back to the core issue of wanting to distinguish between `iPad` and `iPhone`, can we do this without making a function called `isMobile`?  This is mainly because I think there will be some debate as to whether an iPad is a mobile device or not (I personally think it probably is).

How do you feel if the following was possible:

```js

const { detect } = require('detect-browser');
const browser = detect();

// handle the case where we don't detect the browser
if (browser) {
  console.log(browser.name);
  console.log(browser.version);
  console.log(browser.os);

  console.log(browser.isVariant('iPad'));
  // true or false
}
```

This `isVariant` implementation would be a very simple test in the first instance.  Basically doing that `indexOf` check in the originally provided UA string, but leaving us the ability to overwrite it for more advanced cases down the line.  Completely gets us away from calling something mobile when someone might disagree also.

Thoughts?

**Comment by DamonOehlman** [comment]
@vstets @euxn23 See PR #70 for an example.

**Comment by 5punk** [comment]
Closing as inactive.
